#!/bin/bash

echo "
JOB_NUMBER="$JOB_NUMBER"
root_dir="$root_dir"
bash_dir="$bash_dir"
python_dir="$python_dir"
r_dir="$r_dir"
resource_dir="$resource_dir"
temp_dir="$temp_dir"
log_dir="$log_dir"
results_dir="$results_dir"

genome_fasta="$genome_fasta"
annotation_gff="$annotation_gff"
annotation_subset="$annotation_subset"
TSS_PLUS="$TSS_PLUS"
TSS_MINUS="$TSS_MINUS"
TES_PLUS="$TES_PLUS"
TES_MINUS="$TES_MINUS"
BODY_PLUS="$BODY_PLUS"
BODY_MINUS="$BODY_MINUS"

LMOD="$LMOD"
SETUP="$SETUP"
ITERATIONS="$ITERATIONS"
KERNEL="$KERNEL"
APPROACH="$APPROACH"

"
